-- MySQL Script generated by MySQL Workbench
-- 06/22/15 02:51:45
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Proyecto.LPII
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto.LPII` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Proyecto.LPII` ;

-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`AsuntoMemorando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`AsuntoMemorando` (
  `idAsuntoMemorando` INT NOT NULL AUTO_INCREMENT,
  `descripcionAsuntoMemorando` VARCHAR(45) NULL,
  PRIMARY KEY (`idAsuntoMemorando`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`EstadoMemorando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`EstadoMemorando` (
  `idEstadoMemorando` INT NOT NULL AUTO_INCREMENT,
  `descripcionEstadoMemorando` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoMemorando`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `descripcionTipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`Distrito` (
  `idDistrito` INT NOT NULL AUTO_INCREMENT,
  `nombreDistrito` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`Sexo` (
  `idSexo` INT NOT NULL AUTO_INCREMENT,
  `descripcionSexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `nombreProvincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`AreaMunicipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`AreaMunicipal` (
  `idAreaMunicipal` INT NOT NULL AUTO_INCREMENT,
  `nombreAreaMunicipal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAreaMunicipal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombresUsuario` VARCHAR(45) NOT NULL,
  `apellidoPaternoUsuario` VARCHAR(45) NOT NULL,
  `apellidoMaternoUsuario` VARCHAR(45) NOT NULL,
  `fechaNacimientoUsuario` DATE NOT NULL,
  `direccionUsuario` VARCHAR(45) NOT NULL,
  `correoUsuario` VARCHAR(45) NOT NULL,
  `telefonoUsuario` VARCHAR(45) NULL,
  `dniUsuario` INT NOT NULL,
  `loginUsuario` VARCHAR(45) NOT NULL,
  `passwordUsuario` VARCHAR(45) NOT NULL,
  `idTipoUsuario` INT NOT NULL,
  `idDistrito` INT NOT NULL,
  `idPais` INT NOT NULL,
  `idSexo` INT NOT NULL,
  `idProvincia` INT NOT NULL,
  `idAreaMunicipal` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_TipoUsuario1_idx` (`idTipoUsuario` ASC),
  INDEX `fk_Usuario_Ditrito1_idx` (`idDistrito` ASC),
  INDEX `fk_Usuario_Pais1_idx` (`idPais` ASC),
  INDEX `fk_Usuario_Sexo1_idx` (`idSexo` ASC),
  INDEX `fk_Usuario_Provincia1_idx` (`idProvincia` ASC),
  INDEX `fk_Usuario_AreaMunicipal1_idx` (`idAreaMunicipal` ASC),
  CONSTRAINT `fk_Usuario_TipoUsuario1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `Proyecto.LPII`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Ditrito1`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `Proyecto.LPII`.`Distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `Proyecto.LPII`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Sexo1`
    FOREIGN KEY (`idSexo`)
    REFERENCES `Proyecto.LPII`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Provincia1`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Proyecto.LPII`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_AreaMunicipal1`
    FOREIGN KEY (`idAreaMunicipal`)
    REFERENCES `Proyecto.LPII`.`AreaMunicipal` (`idAreaMunicipal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`Memorando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`Memorando` (
  `idMemorando` INT NOT NULL AUTO_INCREMENT,
  `fechaMemorando` DATE NOT NULL,
  `contenidoMemorando` TEXT NULL,
  `AsuntoMemorando_idAsuntoMemorando` INT NOT NULL,
  `EstadoMemorando_idEstadoMemorando` INT NOT NULL,
  `idUsuarioRemitente` INT NOT NULL,
  `idUsuarioDestinatario` INT NOT NULL,
  PRIMARY KEY (`idMemorando`),
  INDEX `fk_Memorando_AsuntoMemorando_idx` (`AsuntoMemorando_idAsuntoMemorando` ASC),
  INDEX `fk_Memorando_EstadoMemorando1_idx` (`EstadoMemorando_idEstadoMemorando` ASC),
  INDEX `fk_Memorando_Usuario1_idx` (`idUsuarioRemitente` ASC),
  INDEX `fk_Memorando_Usuario2_idx` (`idUsuarioDestinatario` ASC),
  CONSTRAINT `fk_Memorando_AsuntoMemorando`
    FOREIGN KEY (`AsuntoMemorando_idAsuntoMemorando`)
    REFERENCES `Proyecto.LPII`.`AsuntoMemorando` (`idAsuntoMemorando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Memorando_EstadoMemorando1`
    FOREIGN KEY (`EstadoMemorando_idEstadoMemorando`)
    REFERENCES `Proyecto.LPII`.`EstadoMemorando` (`idEstadoMemorando`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Memorando_Usuario1`
    FOREIGN KEY (`idUsuarioRemitente`)
    REFERENCES `Proyecto.LPII`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Memorando_Usuario2`
    FOREIGN KEY (`idUsuarioDestinatario`)
    REFERENCES `Proyecto.LPII`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto.LPII`.`TallerMecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto.LPII`.`TallerMecanico` (
  `idTallerMecanico` INT NOT NULL AUTO_INCREMENT,
  `nombreTallerMecanico` VARCHAR(45) NOT NULL,
  `direccionTallerMecanico` VARCHAR(45) NULL,
  `telefonoTallerMecanico` VARCHAR(45) NULL,
  PRIMARY KEY (`idTallerMecanico`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
